### ISSUE TITLE
default settings for create new line

### ISSUE THREAD

**Issue by MarcovanderLinden** [conveyal/analysis-ui#107]
The default setting for creating a new line is "creating new stops" checked, "bidirectional" unchecked. In my experience, all new lines are bidirectional and have predefined stops, so it's not usefull to have automated stops. My suggestion is to check bidirectional by default and leave create stops automaticly empty by default.

**Comment by abyrd** [comment]
I would agree with these defaults. The "create stops automatically" is really only used in very special circumstances, and usually the user should be thinking about true stop placement.

**Comment by mattwigway** [comment]
I agree with the bidirectional default. However I find that I almost always use "create stops automatically" when specifying a scenario. That said, it's not difficult to toggle it on.

**Comment by abyrd** [comment]
Personally I find "create stops automatically" kind of dangerous as a source of artificial precision. We're going to a lot of trouble to account for all the potential schedules a frequency route could have, and all the possible wait times someone could encounter, but we're freezing the stops at arbitrary locations. I suspect if you could evaluate all the possible stop placements with an average of M meters between stops, it would be a large source of variation in the results. I'd discourage people from using it as much as possible - that's why I'd prefer it to be off by default.

**Comment by mattwigway** [comment]
Fair point. Let's turn it off.

Although maybe we should monte carlo draws on stop placement? Probably not,
because they're definitely not random in the real world.

On Mon, Jun 6, 2016 at 5:27 PM, Andrew Byrd <notifications@github.com>
wrote:

> Personally I find "create stops automatically" kind of dangerous as a
> source of artificial precision. We're going to a lot of trouble to account
> for all the potential schedules a frequency route could have, and all the
> possible wait times someone could encounter, but we're freezing the stops
> at arbitrary locations. I suspect if you could evaluate all the possible
> stop placements with an average of M meters between stops, it would be a
> large source of variation in the results. I'd discourage people from using
> it as much as possible - that's why I'd prefer it to be off by default.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/107#issuecomment-224093714>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAimrvggjRsEoJOUUXwxuMYQlEpE9aFHks5qJJCsgaJpZM4Ip0bC>
> .
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC
