### ISSUE TITLE
Idea: Remove "auto-save" from modifications in favor of a manual save

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#1282]
Auto-save prevents "undoing" changes. If a user accidentally makes changes that they want to undo, theres no way to prevent the save. 

1. Keep the "Save on return to Modifications" action
2. Add an additional state indicating unsaved changes
3. Add buttons to "commit" or "discard" the changes

**Comment by abyrd** [comment]
I do find that even though I know it auto-saves, every time I finish a modification I find myself looking for a way to save it, or at least confirm that it has been saved before I navigate away. Rather than a back arrow (which feels a bit like abandoning your changes) I think we should clearly label the button as "save and return to modifications". Another button could revert to last saved version. Very good point about being able to revert to a known state, it's easy to start working on something and realize you've put in wrong figures, and want to just go back to "the way things were".

**Comment by ansoncfit** [comment]
As just discussed, this may help resolve database write issues.

**Comment by trevorgerhardt** [comment]
Closed in #1572
