### ISSUE TITLE
Request times out when viewing large regional analysis for the first time

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#393]
When a regional analysis is finished, there is no indication that it's still working on combining all the results for all the origins, just an error in the console.

**Comment by mattwigway** [comment]
There is no longer a step of combining all results, this is done while the results come back. Can you elaborate on the error you're seeing?

**Comment by abyrd** [comment]
What we saw was that the analysis was finished (progress bar gone), but when asking to display the results an HTTP error code was reported in the JS console. This might have simply been a 504 indicating that it took a long time to extract/encode the response, since this was a large grid. It should be easy to reproduce.

**Comment by mattwigway** [comment]
So I believe what is happening here is that analysis-backend is collating all the results to extract just the point estimate without all the bootstraps, and that causes a frontend timeout. We could just perform this extraction as soon as the regional analysis completes.

**Comment by landonreed** [comment]
As a related issue, when viewing a corrupted regional analysis (e.g., something ran out of memory while processing the job) there is no indication to the user that something is broken.  Just a blank screen.

This is related because there's really no way to differentiate whether the results are still be collated or they're just rubbish (other than just waiting some long, arbitrary period of time to see if it works).

**Comment by abyrd** [comment]
We should never even allow displaying regional analyses that didn't finish properly.

**Comment by landonreed** [comment]
Yes, exactly.  They should not be clickable in the list with an error icon showing that failure occurred.  The only option should be to delete them.

**Comment by trevorgerhardt** [comment]
No longer relevant.
