### ISSUE TITLE
Regional analysis export fails

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#403]
@chourmo reports that under the new scenario editor / Analysis he cannot export regional analysis results to SIG format.

A new empty window opens but nothing is displayed or downloaded. The same problem exists on both Chrome and Firefox.

![image001](https://cloud.githubusercontent.com/assets/112871/26587448/bcb8a64a-4552-11e7-9404-2a0396029e97.jpg)

**Comment by abyrd** [comment]
@trevorgerhardt or @mattwigway, any guess what's happening here?

**Comment by mattwigway** [comment]
I don't think any of those errors are relevant, are there any network
errors?

**Comment by mattwigway** [comment]
So it looks like this is because the backend url that is being requested by the frontend does not match what the latest version of the backend expects. If you watch the network console you'll see a request for something like `https://analysis.conveyal.com/api/regional/9020fde9-63a8-45dd-9536-a623cbefb92c/grid/mean/tiff?redirect=false` , that should not have the text `mean` in it. @trevorgerhardt may be able to fix this or you can just edit the URL and request with curl as long as you make sure the auth header gets in there (you can use the copy as curl option in the chrome network pane and then edit the url).
