### ISSUE TITLE
Uploading custom grid gives insufficient status feedback and requires reload 

### ISSUE THREAD

**Issue by landonreed** [conveyal/analysis-ui#463]
When uploading a custom opportunity grid, if the grid is large enough, the user will need to reload page.  This means there is insufficient feedback about the status of the job.

cc @abyrd @trevorgerhardt

**Comment by ansoncfit** [comment]
There is also insufficient feedback about missing files.  Users should be notified if a required file (e.g. `.prj`) is missing, rather than having upload fail silently.

**Comment by ansoncfit** [comment]
Now seeing an error:

![image](https://user-images.githubusercontent.com/2173529/31902995-c1885c3c-b7f4-11e7-82f1-f1d55cdab271.png)

**Comment by ansoncfit** [comment]
This issue was recently addressed in https://github.com/conveyal/analysis-ui/pull/528

![image](https://user-images.githubusercontent.com/2173529/32452140-bcc36a3c-c2e6-11e7-96cb-37fda6a243b3.png)

But it says an upload started five hours ago when I just started one.  Any ideas, @trevorgerhardt ?  I think this is close to closing.

**Comment by trevorgerhardt** [comment]
My guess is that I used the wrong Java date/time format so the `timeDistanceInWords` function parsed UTC hours. We can keep this open for that issue or create a new, specific ticket 👍

**Comment by ansoncfit** [comment]
Opened https://github.com/conveyal/analysis-ui/issues/556
