### ISSUE TITLE
Analysis date out of GTFS validity

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#478]
The default value of the date of analysis is "Today". It can be out of the valid range of dates in the GTFS Bundle. The analysis produces bogus results.

The default date should be in the valid range in the GTFS bundle, which could be either calculated or an input in the "configure panel settings" panel.

**Comment by abyrd** [comment]
This is indeed a problem. In fact I think the default analysis date should be set at the project level.

**Comment by abyrd** [comment]
This problem has struck again - we just did some enormous regional analysis in the Netherlands, but all on "today" rather than the right day, the day when the feeds are valid. We need to assign a default day of analysis per GTFS bundle.

**Comment by ansoncfit** [comment]
+1 for @abyrd's suggestion that the exemplar date be set at the project level.  Perhaps the user can specify at project creation, with warnings appearing later at bundle creation if any feed does not contain the chosen date.

Related to https://github.com/conveyal/gtfs-lib/pull/37 ?

**Comment by abyrd** [comment]
A core problem though is that the date coverage of feeds is usually not clear. Date ranges can be declared in the feed, but those are optional and can be incorrect. I'm updating the functionality in our gtfs-lib that analyzes the number of trips on each date, so that should be available in future versions.

**Comment by abyrd** [comment]
I and other people also regularly make hand-rolled feeds that have validity dates from 2000-2100, which is not going to tell you much. I guess if it defines the same service for those 100 years, it means it's useable since analysis can be performed on any of those days. 36500 rows of data just to say there's the same service every day is a little wasteful, but then again 36k of anything on a current computer is pretty much a non-problem.

**Comment by abyrd** [comment]
This is being taken care of in gtfs-lib as indicated above

**Comment by ansoncfit** [comment]
See also #600.

We get at least one support request per week where this comes up, so it's probably worth a short-term fix (of just defaulting to the last analysis date used) before longer-term gtfs-lib fixes are in place.

**Comment by trevorgerhardt** [comment]
We really should just set all of the analysis settings by "last used"

**Comment by abyrd** [comment]
Agreed, all settings should default to the last one used, especially since it's so easy to hop between pages/tabs in the web app and we'd like things to remain unchanged when we come back to the analysis tab. But we also need to check the selected date against the range of active dates in the feed.
