### ISSUE TITLE
Accessibility values are slightly lower in regional analyses than in single-point analyses

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#612]
This may be an off-by-one issue, with either cutoff minutes or percentiles.  For the example origin below, the values of a regional analysis with a cutoff of 60 minutes seem closer to the values of a single-point analysis with a 59 minute cutoff:

![image](https://user-images.githubusercontent.com/2173529/34394417-d081d186-eb0d-11e7-9a8a-40e28c5e829b.png)
(60 minute cutoff: less than 760,000)

![image](https://user-images.githubusercontent.com/2173529/34394453-172b0ba2-eb0e-11e7-98d6-3eec52d4dee2.png)
(60 minute cutoff: almost 770,000)

![image](https://user-images.githubusercontent.com/2173529/34394476-358deb14-eb0e-11e7-8665-daf662ebb42b.png)
(59 minute cutoff: less than 760,000)

**Comment by ansoncfit** [comment]
See comments in TravelTimeReducer#findPercentileIndex:

>        // FIXME truncate rather than rounding.
>        // TODO check the difference in results caused by using the revised formula in both single and regional analyses.

**Comment by ansoncfit** [comment]
When calculating accessibility totals, R5 checks whether the time to a target is strictly less than the cutoff (see https://github.com/conveyal/r5/blob/97fca5923a95dac2e22f574d45c0d208bc00ed45/src/main/java/com/conveyal/r5/analyst/TravelTimeReducer.java#L151).

Does the front-end use less than or equal to?

That would help explain the Boston examples above, and some recent examples I tested in New York.

**Comment by abyrd** [comment]
I saw this `<=` comment recently as well as one justifying the use of `<` and I was convinced that `<` was the correct operator. The reason is that travel times are converted to integer minutes before the comparison occurs, and truncated toward zero. So values of 60 minutes correspond to times originally in seconds where 60 min <= t < 61 min. It's more accurate to not include those times. The nuance is slightly different if comparing in seconds. It might be less error-prone to convert our time cutoffs to seconds and perform all our comparisons in seconds rather than converting the travel time to minutes and losing precision during the comparison.

**Comment by trevorgerhardt** [comment]
Next step should be to find instances where we are using `<=` in the front end for single point analysis. Possibly in jsolines? If a change to `<` corresponds to the same values in a regional analysis and single point then we should make that change.

**Comment by ansoncfit** [comment]
The accumulation process on the back-end (regional analyses) uses `double` opportunity values, while the accumulation process on the front-end (single-point) uses `integer`s. But this would tend to make regional results higher than single-point results, which is the opposite of the observed problem.

We've confirmed together that `<` use is consistent in the front-end and R5 code.

As a next step, let's dump the grid values to ensure they are coherent between front-end and R5.

**Comment by ansoncfit** [comment]
Amendment to the previous comment: R5 effectively uses integers when incrementing accessibility, because the doubles are truncated to ints when grids are written/read.

Another step: set single-point origins at exact grid-cell centers and compare values (to ensure the observed discrepancy is not due to initial time to access nearest street edge.

**Comment by ansoncfit** [comment]
Idea from @abyrd:
> Get accessibility from the worker for single point. This allows applying distance decay and removing computations from the UI side. Locks the destination grid but that seems harmless.

**Comment by ansoncfit** [comment]
See also our discussion about multi-cutoff vs. single-cutoff results.

**Comment by trevorgerhardt** [comment]
@abyrd @ansoncfit was this issue fixed with the latest changes in r5 that addressed the multi cutoff issues?

**Comment by abyrd** [comment]
I wouldn't expect there to be a connection with the routing (route re-boarding) issues that were fixed, since the UI receives the same travel time outputs used by the backend. I guess it's possible that slight differences in the regional and single point code paths might have led to different routes being arbitrarily excluded in the different cases.

But our planned shift to computing single point accessibility on the worker (originally to accommodate one-second-resolution decay functions) will certainly resolve this issue. So I'd be in favor of leaving this open until we switch to worker-side accessibility computation, at which point we can consider it solved at the root.

**Comment by ansoncfit** [comment]
In discussions related to https://github.com/conveyal/analysis-backend/pull/261 and https://github.com/conveyal/analysis-ui/pull/1251, @abyrd and @trevorgerhardt have agreed on how array positions should be interpreted and eliminated a number of off-by-one and `<` vs. `<=` ambiguities. With changes in those PRs, the frontend functions (for single-point results) match the backend ones (for regional results), so this issue can be closed.

Given that we will continue to maintain the frontend code for loading grids and calculating accessibility for old worker versions, we will keep all step-function accessibility calculation in the frontend, and signal to the backend that it does not need to do the calculation by removing the `destinationPointSetId` from the analysis request when the step function is selected.

So the frontend will continue to calculate accessibility for traditional hard-cutoff (step function) indicators, and the worker will calculate accessibility for other step functions, where one-second resolution is required. Note that for the step function (where weight steps from 1 to 0 at minute boundaries), one-second resolution is superfluous.

**Comment by abyrd** [comment]
I just tested regional analysis TIFF exported results against single point numbers shown in the UI, both using the step function. At every point I checked, I saw exactly the same results from single point as from the regional analysis. Also verified that the UI was not receiving accessibility numbers in the responses from the backend, so as intended the UI is calculating its own numbers that exactly match the workers. Jumping back and forth between different decay functions and opportunity data sets in the UI seems to be working well.
