### ISSUE TITLE
When extending route, don't wait until click to show extension

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#646]
@demory notes that when editing route alignments, other tools helpfully show a reduced-opacity path, which follows the hovering cursor and shows the segment about to be added.  

We'll need to investigate how well this works with graphhopper when follow streets is enabled.

**Comment by Nate-Wessel** [comment]
This would be helpful. I keep accidentally extending routes from the wrong side, making them double back on themselves. Showing the alignment before clicking would generally prevent this. 

For a bidirectional route, it isn't otherwise obvious which end one would extend from with the two options available (extend vs. extend from end) unless you remember/know how it was originally drawn.

**Comment by ansoncfit** [comment]
Probably not worth addressing unless we decide to implement in-house follow-streets routing. That could be useful for custom OSM, but it's not yet on our roadmap.
