### ISSUE TITLE
Import modifications from another project

### ISSUE THREAD

**Issue by erathal** [conveyal/analysis-ui#659]
I have a region setup with multiple projects. In one of the projects, I defined a modification (additional trip pattern). However, when trying to import this modification from another project within the same region, the dropdown list is empty.

**Comment by ansoncfit** [comment]
Was the project from which you were trying to import a modification based on the same bundle?  By design, only modifications that are applied to the same bundle are able to be imported, because it's not guaranteed that object identifiers would be consistent between bundles.

That being said, adding purely new routes/trips should be allowed (see https://github.com/conveyal/analysis-ui/issues/645)

**Comment by ansoncfit** [comment]
Raw json for modifications can be copy/pasted between projects as of https://github.com/conveyal/analysis-ui/pull/847
