### ISSUE TITLE
Revised stop location not saved to scenario

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#687]
1. Isochrone as expected with add-trip modification and stop at (lat1, lon1):
![image](https://user-images.githubusercontent.com/2173529/39826157-c9c0490e-5381-11e8-8290-012208ae0030.png)

2. After the stop is moved, the isochrone still suggests the stop is in the old location.  Inspecting the scenario processed by the backend shows the stop coordinates are still (lat1, lon1)
![image](https://user-images.githubusercontent.com/2173529/39826315-3a5f204a-5382-11e8-80bf-37a65c624c25.png)

3. Unchecking, then checking "Active in Scenario 1" for this modification makes it work as expected, with the back end receiving the updated (lat2, lon2). 
![image](https://user-images.githubusercontent.com/2173529/39826517-fb6a951c-5382-11e8-8fef-4b84322979fa.png)

**Comment by trevorgerhardt** [comment]
I was unable to reproduce this after repeating the prescribed steps. Is it possible that this was fixed recently or that there was a missed error that caused it not to save correctly initially?

**Comment by trevorgerhardt** [comment]
Urg. I'm having trouble reproducing this again. I remember watching it happen via screen share. Were we sure that it wasn't caused by just a slow internet connection? If that's possible we may want to discuss fully disallowing any actions while data is being returned. This would help prevent nonce errors also. For cases like #752 and "Editing Alignments" we would probably need to batch the updates into one to keep it usable.

**Comment by ansoncfit** [comment]
Despite repeated attempts, including with Chrome DevTools networks speed set to slow 3G, I have not been able to reproduce this either.  Closing for now.
