### ISSUE TITLE
Ensure hops are selected on all selected routes of an adjust-speed modification

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#697]
An MIT user reports:

> When I selected all routes, they did appear in the list of routes in the modification JSON, but they did not visualize and drawing polygons always resulted in an empty array for hops. So I ended up selecting the routes one by one. 

This, along with #696, makes me wonder whether hops are correctly being selected for all routes in an adjust-speed modification, or just the first.

**Comment by trevorgerhardt** [comment]
Looking through old tickets...when "all routes" are selected should we even allow selecting individual stops? 

If they want to select individual stops, we should force users to select individual routes also. So "All Routes" would be "All Routes and Stops".

@ansoncfit @abyrd what do you think?

**Comment by abyrd** [comment]
@trevorgerhardt there's definitely a use case for removing stops from all routes. Say a station complex is going to be closed for 6 months for construction - all train platforms and every bus stop in the station are not going to be available. It is convenient to geometrically select all those stops and remove them from every route, i.e. any route that happens to use them.

Otherwise you have to somehow figure out all routes passing through those stops, select those routes, then select the stops, and risk missing some routes that happen to pass through one of the stops.

**Comment by trevorgerhardt** [comment]
I'm still unclear about what we want to do with this issue. 

What exactly is going wrong? What changes are we looking to implement?

**Comment by abyrd** [comment]
My understanding is that a user selected "all routes" in an adjust-speed modification and expected to be able to select specific hops that the modification would apply to, but something about the UI prevented the user from selecting specific hops.

I just tried out this functionality to observe behavior when multiple routes are selected. When you select a single route, that route is displayed on the map. If you select additional routes, only the first route you selected continues to be displayed on the map. Only when you de-select that single route that is being displayed will switch to displaying another route in the set.

Once multiple routes are selected, the segment selection tools are still available. This allows you to add and remove segments that will be affected by the modification, but the map is showing only one of the N routes that have been selected. 

So there is a contradiction between the fact that on one hand, multiple routes are selected, and on the other hand, the segment selection tools only display and affect one arbitrary route in that list. It's not clear to the user what the result would be of selecting more than one route to be affected, but only selecting segments from one of those N routes.

Internally (peeking into the modification JSON) every selected route is listed, but only the segments selected from the one arbitrary route which is displayed will be listed.

**So, the overall effect is:** the route display and segment-choosing tools show only one route even when two or more routes are selected. This never gives an accurate visual representation of what is actually being affected by the modification (unless the user selects specific segments of the one route that happens to be displayed, in which those specific segments between those exact stop IDs would be affected on all routes).

**The possible solutions are:** When multiple routes are selected, we would need to either display all segments of all selected routes, or not display any of them at all. Additionally, we would need to make the segment selection tools able to select any segment in any route, or disable it entirely. Otherwise, what the user sees visually does not reflect internal behavior.

**The most straightforward solution is:** entirely disable and hide the segment selection tools when multiple routes are selected (including "all routes"), showing a message saying segment selection is only available for single routes.
