### ISSUE TITLE
Generate docs on each PR

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#953]
Probably switch away from ReadTheDocs and use something like https://v2.docusaurus.io/

**Comment by Nate-Wessel** [comment]
Would this support Sphinx? I've been making use of some of Sphinx's features beyond just standard markdown in #960. Referencing, glossary terms, etc.

**Comment by trevorgerhardt** [comment]
Can you show me an example? I am not familiar with Sphinx

**Comment by trevorgerhardt** [comment]
The docs are mostly markdown files that can easily be consumed by the same JavaScript library that runs the site (Next.js). I have an idea in mind for the future where we can show the relevant page/section of a page right in the app in a modal or [drawer](https://chakra-ui.com/drawer). But that would require the docs to be processable without python.

**Comment by trevorgerhardt** [comment]
A better first step towards automatic document generation would be to switch to https://www.mkdocs.org/ with a ReadTheDocs theme.

**Comment by Nate-Wessel** [comment]
For example: 
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html#create-a-glossary
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-a-custom-anchor
Sphinx makes it a lot easier to do cross-referencing within the docs, without having to specify full URLs. It's a lot like LaTeX, if you're familiar, where you can place a short label and reference it from anywhere else. No need to type out a long, potentially unstable heading as part of an id. 

If I use a term that may be ambiguous in context, I can just reference the glossary like 
```
:term:`GTFS bundle`
```
rather than e.g.

`[GTFS bundle](../glossary.html#gtfs-bundle)`
(which hopefully hasn't moved in the meantime)

**Comment by trevorgerhardt** [comment]
Docs have been moved to https://github.com/conveyal/docs
