### ISSUE TITLE
Add ability to show/hide all modifications

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#975]
I think this issue is the opposite of #109, where the problem was that there was no way to hide all modifications. Now there is no way to _show_ all modifications. Each has to be clicked individually.

The hide-all icon (below) should be paired with a show-all icon.

![Screenshot_2020-01-15_13-00-08](https://user-images.githubusercontent.com/7830465/72458736-28a96180-3797-11ea-870c-2f70eeae60a0.png)

**Comment by trevorgerhardt** [comment]
We intentionally do not have this. In instances where projects end up with hundreds of modifications, attempting to show them all at once can crash the application.

**Comment by ansoncfit** [comment]
Projects with hundreds of modifications are the exception, not the rule. 

Could we add some conditional logic, so that the visibility icons for the project and each scenario would show all modifications up to some limit x and show a warning that only x are shown if more are requested?

On a related note, with such limits in place, we could safely return to the practice of showing modifications on the map by default (which would also help with #1057). For users who aren't aware that modifications are saved automatically, it's a bit disconcerting to navigate back to the modification list after creating a modification and not see what they just created.
