### ISSUE TITLE
Opportunity upload status messages persist through page refresh

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#990]
When uploading multiple opportunity datasets, some of the status messages ("processing", "done") persist after the page is refreshed. 
![Screenshot_2020-01-25_12-00-41](https://user-images.githubusercontent.com/7830465/73124665-cd802780-3f6b-11ea-9c1b-e172ef3d602c.png)

That is, they will disappear after a refresh, but all of them (plus a new one) will reappear again when a new dataset is uploaded. This is true even if I do a hard refresh with shift+control+R.

Clicking the `X` will make them go away permanently and clicking the refresh link in the status itself will sometimes throw an error which is visible for a second before the page refreshes:
![Screenshot_2020-01-25_12-21-10](https://user-images.githubusercontent.com/7830465/73124773-459b1d00-3f6d-11ea-91de-0cafb1269a10.png)

The blue processing message in the screenshot above does not have an `X` to click and will not go away. I also saw some of these messages briefly after switching to a different region and uploading data there.

**Comment by trevorgerhardt** [comment]
@Nate-Wessel, created a PR addressing the reloading and lingering displaying when switching regions. 

The other issues you mention here are intentional, statuses need to be cleared manually. 

Currently progress reporting across the application is done in a variety of ways. We know that it's not done the best way it can be. If you have specific recommendations that aren't really bugs for small changes to the way things are done, please open up subsequent issues there. 🙏
